steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build and Tag'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/$PROJECT_ID/career-analyzer-repo/career-analyzer-image:$SHORT_SHA',
    'app'
  ]


- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Image'
  args: [
    'push',
    'us-central1-docker.pkg.dev/$PROJECT_ID/career-analyzer-repo/career-analyzer-image:$SHORT_SHA'
  ]


- name: 'gcr.io/cloud-builders/gke-deploy'
  id: 'Deploy to GKE'
  args:
  - 'run'
  - '--filename=k8s/deployment.yaml'
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/career-analyzer-repo/career-analyzer-image:$SHORT_SHA'
  - '--location=us-central1'
  - '--cluster=resume-analyzer-gke-cluster'
  - '--timeout=5m'
options:
  logging: CLOUD_LOGGING_ONLY
