apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: resume-analyzer
          image:  us-central1-docker.pkg.dev/strange-firefly-475810-h9/career-analyzer-repo/career-analyzer-image:v4
          command: ["gunicorn"]
          args: ["--bind", "0.0.0.0:5000", "--timeout", "300", "app:app"]
          env:
            - name: GEMINI_API_KEY
              value: "AIzaSyBqBqJnskZx-YdurWWsoZ2cDLy7vdq_GE8"
          ports:
            - containerPort: 5000
